### ISSUE TITLE
Using policies for footprints

### ISSUE THREAD

**Issue by cesar2064** [trailsjs/trails-policy#4]
Hi, Is it possible to create policies for footprints?, because actually it works only for defined controller methods.

config/policies.js

```
module.exports = {
  UserController:{
    helloWorld:["Auth.checksAuthentication"],
    find:["Auth.checksAuthentication"],
    create:["Auth.checksAuthentication"]
  }
}
```

when I try to access /user/helloworld, the checksAuthentication is executed, but when I access 
/get /api/v1/user or /post /api/v1/user, the function isn't executed.

**Comment by cesar2064** [comment]
finally I could execute the policy for footprints, but after that I realized that I have to check the url and methods of the request object in the policy for doing something according the footprint model.

config/policies.js

```
module.exports = {
  FootprintController:{
    find:["Auth.checkAuth"],
    create:["Auth.checkAuth"]
  }
}
```

api/policies/Auth.js

```
module.exports = class AuthPolicy extends Policy {
  checkAuth(req,res,next){

    let url = req.url
    let method = req.method

    if(url = "/api/v1/user")
      if(method = "GET")  

  }
}
```

is that the best way to do that?

**Comment by wbprice** [comment]
At the moment, the only way to use a policy with Footprint-generated routes is to apply a single policy to the FootprintsController in `config/policies.js`

```
FootprintController: [ 'Footprint.test' ]
```

Within the policy file `api/policies/Footprint.js`, you can use `request.params.model` to write policies for specific routes.

**Comment by cesar2064** [comment]
Ok thanks @wbprice .
